name: 考研倒计时邮件发送

on:
  schedule:
    # 每天早上8点执行（北京时间早上8点 = UTC时间凌晨0点）
    # 北京时间 UTC+8，所以北京时间8点对应UTC时间0点
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  send-mail:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
    
    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 调试配置信息
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python debug_config.py

    - name: 发送倒计时邮件
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python exam_countdown.py

    - name: 检查执行结果
      if: failure()
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        echo "邮件发送任务失败，尝试发送错误通知..."
        python test_error_notification.py || echo "错误通知发送也失败了"