name: 考研倒计时邮件发送

on:
  schedule:
    # 每天早上8点执行（UTC时间，北京时间需要-8小时，所以设置为0点）
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  send-mail:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
    
    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install openai
        
    - name: 发送倒计时邮件
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python exam_countdown.py